### ISSUE TITLE
column "date" is of type date but expression is of type text

### ISSUE THREAD

**Issue by nicokant** [NINAnor/seabird-gps-database#18]
This error seems to happen with `IgotU_Shag_Sklinna_2011-2022 ` with ring number `295820`.
It's not clear why this happens, the row doesn't seem different from the previous or the next.

**Comment by nicokant** [comment]
fixed in 42bd61f81d29ddb0a9d48f685cdbec638fb958fa

**Comment by vilde-oddvik** [comment]
I am still getting this error when trying to upload that particular spreadsheet.

**Comment by vilde-oddvik** [comment]
Any new thoughs on this issue? If there is no solution we might need to consider removing the row with this ring number

**Comment by vilde-oddvik** [comment]
I just figured out that the error must be related to "other sensors", because I just got the same error in another metadata file, and the "problem row" in both files are the first individuals in the excel sheet that has a accelerometer deployed.

This is the new file with same error:
[Brünnich's Guillemots_Svalbard_2012-2016+2018_v6.xlsx](https://github.com/user-attachments/files/15909629/Brunnich.s.Guillemots_Svalbard_2012-2016%2B2018_v6.xlsx)

**Comment by vilde-oddvik** [comment]
I just got another metadata file with similar issue, this time:

code    hint     message
42804 | None | column "date" is of type date but expression is of type integer

This one also have "other sensor deployed" which is likely to be linked to the issue (see comment above)

File with issue: 
[Shag_Jarstein_2024_v6.2.xlsx](https://github.com/user-attachments/files/22040591/Shag_Jarstein_2024_v6.2.xlsx)
